server:
  port: 9060

spring:
  application:
    name: auth2.0-center
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/zuul-auth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    refix: classpath:/templates/
    suffix: .html
    mode: HTML5
  profiles: oauth

eureka:
  instance:
    prefer-ip-address: true 
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://admin:admin@exdl1:8765/eureka/,http://admin:admin@exdl2:8765/eureka/,http://admin:admin@exdl3:8765/eureka/

endpoints:
  health:
    sensitive: false
    enabled: true

management:
  security:
    enabled: false

security:
  oauth2:
    resource:
      filter-order: 3
logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        web: info
  
